### ISSUE TITLE
sqlite3 hates excel created CSVs

### ISSUE THREAD

**Issue by elliewix** [datapraxis/sourcecaster#1]
I've confirmed this on macs and windows during SWC SQL lessons.

To replicate:
- Save a CSV via Excel:  failtown.csv with the content:

```
one, two, three
1, 2, 3
1, 2, 3
```
- launch `sqlite3` in directory with said csv
- `.mode csv`
- `.import failtown.csv failtown`
- You'll get an error like: `CREATE TABLE wb(...) failed: duplicate column name: 2`
- You may not get an error if the file does not contain duplicate datapoints in the columns, but if you do .schema every data point will be a column name.

What's happening here is that sqlite3 is expecting newlines to be \n but Excel creates them with \r.  So sqlite3 just sees one long line of column names, rather than a table.  Pop failtown.csv open in Python and you can see the glory:

```
>>> with open('failtown.csv', 'rt') as fin:
...     fin = fin.read()
... 
>>> fin
'one,two,three\r1,2,3\r1,2,3' 
```

One way to fix this is to attempt and copy/paste the contents in a new text file.  Or you can do command line magic: https://twitter.com/elliewix/status/714466345543471105

`cat wb.csv | tr -s '\r' '\n' > wbtr.csv`

Better bash gurus than I could make this more elegant, but it works.

```
I:Documents wickes1$ cat failtown.csv | tr -s '\r' '\n' > failtownfixed.csv
I:Documents wickes1$ sqlite3
SQLite version 3.9.2 2015-11-02 18:31:45
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .mode csv
sqlite> .import failtownfixed.csv failtown
sqlite> .schema
CREATE TABLE failtown(
  "one" TEXT,
  "two" TEXT,
  "three" TEXT
);
```

**Comment by thomasgpadilla** [comment]
This level of documentation is super inspiring. Tested workflow, and all is good. Will model this approach in my own work. Implementing addition of command now.

**Comment by drjwbaker** [comment]
@elliewix I think I've encountered this outside a sqlite error context. Thanks so much for suggesting. Will proper find myself using this!

**Comment by issamux** [comment]
thanks , that help me to import cvs to sqlite database 👍

**Comment by elliewix** [comment]
Excellent! Don't forget to recast any numerical goodies else RIP your sorting.
